driver:
  name: vagrant

platforms:
  - name: ubuntu-16-04-x64
    driver_config:
      region: ams1
      size: 512mb
      server_name: chef-repo-test

suites:
  - name: full-stack
    run_list:
      - role[postgresql]
    postgresql:
      user: "postgres"
      version: "9.5"
      database: "test"
      contrib:
        packages: ['postgresql-contrib-9.5']
    pg_hba: []
    config:
      listen_addresses: "localhost"
      port: "5432"