#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

#  cookbook 'postgresql', '~> 7.1.0'
   # cookbook 'openssl', '= 2.0.0'
   # cookbook 'build-essential', '~> 8.1.1'

  cookbook 'postgresql', path: "site-cookbooks/postgresql"
# cookbook 'postgresql-cluster', '~> 0.3.0'
# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
